var largeParagraph = [
	"You, flock of seagulls, you know why we're here? Why don't you tell my man Vincent where you got the shit hid at? It's over th... I don't remember askin' you a Goddamn thing! You were saying?  It's in the cupboard. No, no, the one by your kn-knees.  We happy? Vincent! We happy? Yeah, we happy. I'm sorry, I didn't get your name. I got yours, Vincent, right? But I didn't get yours... My name's Pitt. And your ass ain't talkin' your way out of this shit. No, no, I just want you to know... I just want you to know how sorry we are that things got so fucked up with us and Mr. Wallace. We got into this thing with the best intentions and I never...I'm sorry, did I break your concentration? I didn't mean to do that. Please, continue, you were saying something about best intentions. What's the matter? Oh, you were finished! Well, allow me to retort. What does Marsellus Wallace look like?",
	
	"What? What country are you from? What? What? Wh - ? 'What' ain't no country I've ever heard of. They speak English in What? What? English, motherfucker, do you speak it? Yes! Yes! Then you know what I'm sayin'! Yes! Describe what Marsellus Wallace looks like! Say 'what' again. Say 'what' again, I dare you, I double dare you motherfucker, say what one more Goddamn time!",
	
	"H-H-He's black...Go on! He's bald...! Does he look like a bitch? What? DOES HE... LOOK... LIKE A BITCH? No! Then why you tryin' to fuck him like a bitch, Brett? I didn't...! Yes, you did. Yes, you did, Brett! You tried to fuck him. No, no...But Marcellus Wallace don't like to be fucked by anybody except Mrs. Wallace.",
	
	"Naw man. I'm pretty fuckin' far from okay. What now? What now? Let me tell you what now. I'ma call a coupla hard, pipe-hittin' niggers, who'll go to work on the homes here with a pair of pliers and a blow torch. You hear me talkin', hillbilly boy? I ain't through with you by a damn sight. I'ma get medieval on your ass. I meant what now between me and you? Oh, that what now. I tell you what now between me and you. There is no me and you. Not no more.",
	
	"Don't you hate that? What? Uncomfortable silences. Why do we feel it's necessary to yak about bullshit in order to be comfortable? That's when you know you've found somebody special. When you can just shut the fuck up for a minute and comfortably enjoy the silence.",
	
	"The path of the righteous man is beset on all sides by the inequities of the selfish and the tyranny of evil men. Blessed is he who, in the name of charity and good will, shepherds the weak through the valley of the darkness, for he is truly his brother's keeper and the finder of lost children. And I will strike down upon thee with great vengeance and furious anger those who attempt to poison and destroy My brothers. And you will know I am the Lord when I lay My vengeance upon you.' Now... I been sayin' that shit for years. And if you ever heard it, that meant your ass. You'd be dead right now. I never gave much thought to what it meant. I just thought it was a cold-blooded thing to say to a motherfucker before I popped a cap in his ass. But I maybe it means you're the evil man. And I'm the righteous man. And Mr. 9mm here... he's the shepherd protecting my righteous ass in the valley of darkness. Or it could mean you're the righteous man and I'm the shepherd and it's the world that's evil and selfish. And I'd like that. But that shit ain't the truth. The truth is you're the weak. And I'm the tyranny of evil men. But I'm tryin', Ringo. I'm tryin' real hard to be the shepherd.",
	
	"Want some bacon? No man, I don't eat pork. Are you Jewish? Nah, I ain't Jewish, I just don't dig on swine, that's all. Why not? Pigs are filthy animals. I don't eat filthy animals. Bacon tastes gooood. Pork chops taste gooood. Hey, sewer rat may taste like pumpkin pie, but I'd never know 'cause I wouldn't eat the filthy motherfucker. Pigs sleep and root in shit. That's a filthy animal. I ain't eat nothin' that ain't got sense enough to disregard its own feces. How about a dog? Dogs eats its own feces. I don't eat dog either. Yeah, but do you consider a dog to be a filthy animal? I wouldn't go so far as to call a dog filthy but they're definitely dirty. But, a dog's got personality. Personality goes a long way. Ah, so by that rationale, if a pig had a better personality, he would cease to be a filthy animal. Is that true? Well we'd have to be talkin' about one charming motherfuckin' pig. I mean he'd have to be ten times more charmin' than that Arnold on Green Acres, you know what I'm sayin'?",
	
	"And you know what they call a... a... a Quarter Pounder with Cheese in Paris? They don't call it a Quarter Pounder with cheese? No man, they got the metric system. They wouldn't know what the fuck a Quarter Pounder is. Then what do they call it? They call it a Royale with cheese. A Royale with cheese. What do they call a Big Mac? Well, a Big Mac's a Big Mac, but they call it le Big-Mac. Le Big-Mac. Ha ha ha ha. What do they call a Whopper? I dunno, I didn't go into Burger King.",
	
	"Jimmie, lead the way. Boys, get to work. A please would be nice. Come again? I said a please would be nice. Get it straight buster - I'm not here to say please, I'm here to tell you what to do and if self-preservation is an instinct you possess you'd better fucking do it and do it quick. I'm here to help - if my help's not appreciated then lotsa luck, gentlemen. No, Mr. Wolf, it ain't like that, your help is definitely appreciated. I don't mean any disrespect, I just don't like people barking orders at me. If I'm curt with you it's because time is a factor. I think fast, I talk fast and I need you guys to act fast if you wanna get out of this. So, pretty please... with sugar on top. Clean the fucking car.",
	
	"Fuck, nigga, what the fuck did you do to his towel? I was dryin' my hands. You're supposed to wash 'em first! You watched me wash 'em. I watched you get 'em wet. I was washing 'em. But this shit's hard to get off. Maybe if I had Lava or something, I coulda done a better job. I used the same fuckin' soap you did and when I got finished, the towel didn't look like no goddamn Maxi-Pad!",
	
	"Whoa, whoa, whoa, whoa... stop right there. Eatin' a bitch out, and givin' a bitch a foot massage ain't even the same fuckin' thing. It's not. It's the same ballpark. Ain't no fuckin' ballpark neither. Now look, maybe your method of massage differs from mine, but, you know, touchin' his wife's feet, and stickin' your tongue in her Holiest of Holies, ain't the same fuckin' ballpark, it ain't the same league, it ain't even the same fuckin' sport. Look, foot massages don't mean shit. Have you ever given a foot massage? Don't be tellin' me about foot massages. I'm the foot fuckin' master. Given a lot of 'em? Shit yeah. I got my technique down and everything, I don't be ticklin' or nothin'. Would you give a guy a foot massage? Fuck you. You give them a lot? Fuck you. You know, I'm getting kinda tired. I could use a foot massage myself. Man, you best back off, I'm gittin' a little pissed here.",
	
	"Mmmm! Goddamn, Jimmie! This is some serious gourmet shit! Usually, me and Vince would be happy with some freeze-dried Taster's Choice right, but he springs this serious GOURMET shit on us! What flavor is this? Knock it off, Julie. What? I don't need you to tell me how fucking good my coffee is, okay? I'm the one who buys it. I know how good it is. When Bonnie goes shopping she buys SHIT. I buy the gourmet expensive stuff because when I drink it I want to taste it. But you know what's on my mind right now? It AIN'T the coffee in my kitchen, it's the dead nigger in my garage. Oh, Jimmie, don't even worry about that...No, No, No, No, let me ask you a question. When you came pulling in here, did you notice a sign out in front of my house that said 'Dead Nigger Storage'? Jimmie, you know I ain't seen no...Did you notice a sign out in front of my house that said 'Dead Nigger Storage'? No. I didn't. You know WHY you didn't see that sign? Why? Cause it ain't there, cause storing dead niggers ain't my fucking business, that's why!",
	
	"Oh, man, I will never forgive your ass for this shit. This is some fucked-up repugnant shit. Jules, did you ever hear the philosophy that once a man admits that he's wrong that he is immediately forgiven for all wrongdoings? Have you ever heard that? Get the fuck out my face with that shit! The motherfucker that said that shit never had to pick up itty-bitty pieces of skull on account of your dumb ass.",
	
	"I got a threshold, Jules. I got a threshold for the abuse that I will take. Now, right now, I'm a fuckin' race car, right, and you got me the red. And I'm just sayin', I'm just sayin' that it's fuckin' dangerous to have a race car in the fuckin' red. That's all. I could blow. Oh! Oh! You ready to blow? Yeah, I'm ready to blow. Well, I'm a mushroom-cloud-layin' motherfucker, motherfucker! Every time my fingers touch brain, I'm Superfly T.N.T., I'm the Guns of the Navarone! IN FACT, WHAT THE FUCK AM I DOIN' IN THE BACK? YOU'RE THE MOTHERFUCKER WHO SHOULD BE ON BRAIN DETAIL! We're fuckin' switchin'! I'm washin' the windows, and you're pickin' up this nigger's skull!",
	
	"Vincent, do you still want to hear my Fox Force Five joke? Sure, but I think I'm still a little too petrified to laugh. No, you wont laugh, 'cus it's not funny. But if you still wanna hear it, I'll tell it. I can't wait. Three tomatoes are walking down the street- a poppa tomato, a momma tomato, and a little baby tomato. Baby tomato starts lagging behind. Poppa tomato gets angry, goes over to the baby tomato, and smooshes him... and says, Catch up.",
	
	"The way your dad looked at it, this watch was your birthright. He'd be damned if any slopes gonna put their greasy yellow hands on his boy's birthright, so he hid it, in the one place he knew he could hide something: his ass. Five long years, he wore this watch up his ass. Then when he died of dysentery, he gave me the watch. I hid this uncomfortable piece of metal up my ass for two years. Then, after seven years, I was sent home to my family. And now, little man, I give the watch to you.",
	
	"Whoa! What the fuck's happening, man? Ah, shit man! Oh man, I shot Marvin in the face. Why the fuck did you do that! Well, I didn't mean to do it, it was an accident! Oh man I've seen some crazy ass shit in my time...Chill out, man. I told you it was an accident. You probably went over a bump or something. Hey, the car didn't hit no motherfucking bump! Hey, look man, I didn't mean to shoot the son of a bitch. The gun went off. I don't know why. Well look at this fucking mess, man. We're on a city street in broad daylight here! I don't believe it. Well believe it now, motherfucker! We gotta get this car off the road! You know cops tend to notice shit like you're driving a car drenched in fucking blood. Just take it to a friendly place, that's all. This is the Valley, Vincent. Marsellus ain't got no friendly places in the Valley. Well Jules, this ain't my fucking town, man!",
	
	"Shit! What you doin'? I'm calling Jimmie, my old partner. He lives in Toluca Lake. Where's Toluca Lake? It's just over the hill here over by Burbank Studios. If Jimmie's ass ain't home, I don't know what the fuck we're going to do, man. 'Cause I ain't got no other partners in 8-1-8. Hey Jimmie, yo! How you doin', man? It's Jules. Listen up man. Me and my homeboy are in serious fucking shit. We're in a car and we gotta get off the road, pronto. I need to use your garage for a couple of hours.",
	
	"Hey kids! How you boys doin'? Hey, keep chillin'. You know who we are? We're associates of your business partner Marsellus Wallace. You do remember your business partner don't you? Let me take a wild guess here. You're Brett, right? Yeah. I thought so. You remember your business partner Marsellus Wallace, don't you, Brett? Yeah, yeah, I remember him. Good. Looks like me an Vincent caught you boys at breakfast. Sorry about that. Whatcha havin'? Hamburgers. Hamburgers! The cornerstone of any nutritious breakfast. ",
	
	"What kind of hamburgers? Ch-cheeseburgers. No, no no, where'd you get 'em? McDonalds? Wendy's? Jack in the Box? Where? Big Kahuna Burger. Big Kahuna Burger. That's that Hawaiian burger joint. I hear they got some tasty burgers. I ain't never had one myself. How are they? They're good. Mind if I try one of yours? This is yours here, right? Mmm-mmmm. That is a tasty burger. Vincent, ever have a Big Kahuna Burger? Wanna bite? They're real tasty. Ain't hungry. Well, if you like burgers give 'em a try sometime. I can't usually get 'em myself because my girlfriend's a vegitarian which pretty much makes me a vegitarian. But I do love the taste of a good burger. Mm-mm-mm. You know what they call a Quarter Pounder with cheese in France? No. Tell 'em, Vincent. A Royale with cheese. A Royale with cheese! You know why they call it that? Because of the metric system? Check out the big brain on Brett! You're a smart motherfucker. That's right. The metric system.",
	
	"I don't wanna hear about no motherfuckin' ifs. All I wanna hear from your ass is, You ain't got no problem, Jules. I'm on the motherfucker. Go back in there, chill them niggers out and wait for the cavalry which should be coming directly. You ain't got no problem, Jules. I'm on the motherfucker. Go back in there, chill them niggers out and wait for the Wolf who should be coming directly.",
	
	"I was looking at myself in the mirror. Uh-huh? I wish I had a pot. You were lookin' in the mirror and you wish you had some pot? A pot. A pot belly. Pot bellies are sexy. Well you should be happy, 'cause you do. Shut up, Fatso! I don't have a pot! I have a bit of a tummy, like Madonna when she did 'Lucky Star,' it's not the same thing. I didn't realize there was a difference between a tummy and a pot belly. The difference is huge. You want me to have a pot? No. Pot bellies make a man look either oafish, or like a gorilla. But on a woman, a pot belly is very sexy. The rest of you is normal. Normal face, normal legs, normal hips, normal ass, but with a big, perfectly round pot belly. If I had one, I'd wear a tee-shirt two sizes too small to accentuate it. You think guys would find that attractive? I don't give a damn what men find attractive. It's unfortunate what we find pleasing to the touch and pleasing to the eye is seldom the same.",
	
	"You're going to give her an injection of adrenaline directly to her heart. But she's got, uh, breastplate so you gotta pierce through that. So what you have to do is, you have to bring the needle down in a stabbing motion. I-I gotta stab her three times? No, you don't gotta fucking stab her three times! You gotta stab her once, but it's gotta be hard enough to break through her breastplate into her heart, and then once you do that, you press down on the plunger. What happens after that? I'm kinda curious about that myself...",
	
	"I think her biggest deal was she starred in a pilot. Pilot? What's a pilot? Well, you know the shows on TV? I don't watch TV. Yeah, but, you are aware that there's an invention called television, and on this invention they show shows, right? Yeah. Well, the way they pick TV shows is, they make one show. That show's called a pilot. Then they show that one show to the people who pick shows, and on the strength of that one show they decide if they want to make more shows. Some get chosen and become television programs. Some don't, become nothing. She starred in one of the ones that became nothing.",
	
	"This was Divine Intervention! You know what 'divine intervention' is? Yeah, I think so. That means God came down from Heaven and stopped the bullets. Yeah, man, that's what it means. That's exactly what it means! God came down from Heaven and stopped the bullets. I think we should be going now. Don't do that! Don't you fucking do that! Don't blow this shit off! What just happened was a fucking miracle! Chill the fuck out, Jules, this shit happens. Wrong! Wrong, this shit doesn't just happen. Do you wanna continue this theological discussion in the car, or at the jailhouse with the cops? We should be fuckin' dead now, my friend! We just witnessed a miracle, and I want you to fucking acknowledge it! Okay man, it was a miracle, can we leave now?",
	
	"Now Yolanda, we're not gonna do anything stupid, are we? You don't hurt him. Nobody's gonna hurt anybody. We're gonna be like three little Fonzies here. And what's Fonzie like? Come on Yolanda what's Fonzie like? Cool? What? He's cool. Correctamundo. And that's what we're gonna be. We're gonna be cool. Now Ringo, I'm gonna count to three, and when I count three, you let go of your gun, and sit your ass down. But when you do it, you do it cool.",
	
	"All right, now you let him go. Yolanda, I thought you said you were gonna be cool. Now when you yell at me, it makes me nervous. And when I get nervous, I get scared. And when motherfuckers get scared, that's when motherfuckers accidentally get shot. You just know, you touch him, you die. Well, that seems to be the situation. But I don't want that. And you don't want that. And Ringo here *definitely* doesn't want that.",
	
	"Look, just because I don't be givin' no man a foot massage don't make it right for Marsellus to throw Antwone into a glass motherfuckin' house, fuckin' up the way the nigger talks. Motherfucker do that shit to me, he better paralyze my ass, 'cause I'll kill the motherfucker, know what I'm sayin'? I ain't saying it's right. But you're saying a foot massage don't mean nothing, and I'm saying it does. Now look, I've given a million ladies a million foot massages, and they all meant something. We act like they don't, but they do, and that's what's so fucking cool about them. There's a sensuous thing going on where you don't talk about it, but you know it, she knows it, fucking Marsellus knew it, and Antwone should have fucking better known better. I mean, that's his fucking wife, man. He can't be expected to have a sense of humor about that shit. You know what I'm saying? That's an interesting point. Come on, let's get into character.",
	
	"Hello. Lance! It's Vincent. I'm in big fuckin' trouble, man. I'm coming to your house. Whoa. Whoa. Hold your horses, man. What's the problem? I've got this chick, she fuckin' O.D.in' on me! Well, don't bring her here! I'm not even fuckin' joking with you, man! Do not be bringing some fucked-up pooh-bah to my house! No choice. She's O.D.in'? She's fuckin' dyin' on me, man! Okay, then you bite the fuckin' bullet, take her to a hospital and call a lawyer. Negative. This is not my fuckin' problem, man! You fucked her up, you fuckin' deal with this! Are you calling me on the cellular phone? I don't know you. Who is this? Don't come here, I'm hanging up the phone! Prank caller, prank caller!",
	
	"Yolanda? How we doin, baby? I gotta go pee! I want to go home. Just hang in there, baby. You're doing' great. Ringo's proud of you and so am I. It's almost over. Tell her you're proud of her. I'm proud of you, Honey Bunny.I love you! I love you too, Honey Bunny.",
,
	
	"Look, do you wanna play blindman? Go walk with the shepherd. But me, my eyes are wide fucking open. What the fuck does that mean? It means, that's it for me. From here on in you can consider my ass retired. Jesus Christ. Don't blaspheme. Goddamn. I said don't do that!",
	
	"So, I hear you're taking Mia out. At Marsellus's request. You met Mia yet? No. What's so fucking funny? Look, I'm not stupid. It's the Big Man's wife. I'm gonna sit across from her, chew my food with my mouth closed, laugh at her fucking jokes, and that's it.",
	
	"So we cool? Yeah, we cool. Two things. Don't tell nobody about this. This shit is between me, you, and Mr. Soon-To-Be- you leave town tonight, right now. And when you're gone, you stay gone, or you be gone. You lost all your L.A. privileges. Deal? Deal. Get your ass out of here.",
	
	"You remember Antoine Roccamora, half black, half Samoan, used to call him Tony Rocky Horror? Yeah, maybe. Fat, right? I wouldn't go so far as to call the brother fat, I mean he got a weight problem. What's the nigger gonna do? He's Samoan.",
	
	"You want to rob banks? I'm not saying I want to rob banks, I'm just illustrating that if we did, it'd be easier than what we've been doing. No more liquor stores? What have we been talking about? Yeah, no more liquor stores. Besides, it ain't the giggle it used to be. Too many foreigners own liquor stores these days. Vietnamese, Koreans, they don't even speak fucking English. You tell them, empty out the register, they don't know what the fuck you're talking about. They make it too personal, one of these gook fuckers is gonna make us kill him. I'm not gonna kill anybody. I don't want to kill anybody either. But they'll probably put us in a situation where it's us or them. And if it's not the gooks, it's these old fucking Jews who've owned the store for fifteen fucking generations, you've got Grampa Irving sitting behind the counter with a fucking Magnum in his hand. Try walking into one of those places with nothing but a phone, see how far you get.",
	
	"You know how they use that gun to pierce your ears? They don't use that when they pierce your nipples, do they? Forget that gun. That gun goes against the entire idea behind piercing. All of my piercings, sixteen places on my body, all of them done with a needle. Five in each ear, one through the nipple on my left breast, one through my right nostril, one through my left eyebrow, one in my lip, one in my clit... and I wear a stud in my tongue. Excuse me, but I was just wondering... why do you wear a stud in your tongue? It's a sex thing. It helps fellatio. Don Vincenzo. Step into my office?",
	
	"Still got your Malibu? Aw, man. You know what some fucker did the other day? What? Fucking keyed it. Oh, man, that's fucked up. Tell me about it. I had it in storage for three years, it was out for five days and some dickless piece of shit fucked with it. They should be fucking killed. No trial, no jury, straight to execution. Boy, I wish I could've caught him doing it. I'd have given anything to catch that asshole doing it. It'd been worth him doing it just so I could've caught him doing it. What a fucker! What's more chickenshit than fucking with a man's automobile? I mean, don't fuck with another man's vehicle. You don't do it. It's just against the rules.",
	
	"Normally, both your asses would be dead as fucking fried chicken, but you happen to pull this shit while I'm in a transitional period so I don't wanna kill you, I wanna help you. But I can't give you this case, it don't belong to me. Besides, I've already been through too much shit this morning over this case to hand it over to your dumb ass.",
	
	"This place? A coffee shop? Why not? Nobody ever robs restaurants. Bars, liquor stores, gas stations... you get your head blown off sticking up one of them. Restaurants on the other hand, you catch with their pants down. They're not expecting to get robbed. Not as expectant anyway. I bet you could cut down on the hero factor in a place like this. Right, just like banks, these places are insured. Manager? He don't give a fuck. He just wants to get you out the door before you start plugging the diners. Waitresses? Fucking forget it! No way they're taking a bullet for the register. Busboys? Some wetback getting paid a dollar-fifty an hour, really give a fuck you're stealing from the owner? See, I got the idea, last liquor store we held up, all the customers kept coming in? Yeah. And you got the idea of taking their wallets. Now that was a good idea. Thank you. Made more from the wallets than we did from the register. Yes, we did. A lot of customers come into a restaurant. A lot of wallets. Pretty smart, eh? Pretty smart.",
	
	"Here, I'll tell you what to do. No no no no man, man I ain't giving her... You... you, you're gonna give her the shot...No, you're gonna give her the shot...I ain't givin' her the shot...Well, I ain't givin' her the shot! I never done this before! Yeah, I ain't ever done it before either, alright? I ain't starting now! Look, you brought her here, and that means that you're giving her the shot. The day that I bring an OD-ing bitch over to your house, then I give her the shot. Give her the shot. Give it to me. Here. Gimme that.",
	
	"I'll be there in two shakes of a lamb's tail. Hurry up, Lance! We're losing her! I'm lookin' as fast as I can! What's he looking for? I dunno. Some book. What're you looking for? A little black medical book! What're you looking for? A little black fuckin' medical book! It's like a textbook they give to nurses. I never saw no medical book. Trust me, I have one. Well, if it's so important, why don't you keep it with the shot? I DON'T KNOW! STOP BOTHERING ME! Listen, while you're looking for it, that girl's gonna die on our carpet! You're never gonna find anything in this mess! I'm gonna fuckin' kill you IF YOU DON'T SHUT UP!",
	
	"Can I help you with somethin'? Shut the fuck up! Hey you just wait a god damn minute now! What the fuck you up to? Come here motherfucker! Feel that sting, big boy? That's pride fucking with you! Gotta fight through that shit! You better kill me! Yeah, somebody gonna get killed. SOMEBODY GONNA GET THEIR FUCKING HEAD BLOWN OFF! Hold it right there, goddammit! It's none of your business, mister! I'm making it my business. Toss the weapon. You don't understand, man! Toss the weapon. Get yer foot of the nigger, put yer hands behind yer head and spproach the counter right now. Zed? It's Maynard. Yeah, spider just caught a couple of flies.",
	
	"How was your breakfast? It was good...Did you get the pancakes, the blueberry pancakes? No, no, they didn't have blueberry pancakes, I had to get buttermilk - are you sure you're okay? Honey, since I left you, this has been without a doubt the single weirdest fucking day of my life! Come on, hop on - I'll tell you all about it.",
	
	"Forget it. Too risky. I'm through doing that shit. You always say that. That same thing every time, 'I'm through, never again, too dangerous'. I know that's what I always say. I'm always right, too. But you forget about it in a day or two. Yeah, well the days of me forgetting are over, and the days of me remembering have just begun.",
	
	"So, tell me again about the hashbars? Okay, what you wanna know? Hash is legal there in Amsterdam, right? Yeah, it's legal, but it ain't a hundred percent legal. I mean, you can't just walk into a restaurant, roll a joint and start puffing away. You're only supposed to smoke in your home or certain designated places. And those are hashbars? Yeah it breaks down like this. It's legal to buy it, it's legal to own it, and, if you're the proprietor of a hash bar, it's legal to sell it. It's still illegal to carry it around, but that doesn't really matter 'cause... get if you get stopped by the cops in Amsterdam, it's illegal for them to search you. I mean, that's a right the cops in Amsterdam don't have. I'm going, that's all there is to it, I'm fuckin' going. Yeah baby, you'd dig it the most.",
	
	"The way it is now, you're taking the same risk as when you rob a bank. You take more of a risk, banks are easier. You don't even need a gun in a federal bank. I mean, they're insured, why should they give a fuck? I heard of this one guy, walks into a bank with a portable phone. He gives the phone to the teller, a guy on the other end of the line says, we've got this guy's little girl, if you don't give him all your money, we're gonna kill her.",
	
	"Did it work? Fucking-A right, it worked. That's what I'm saying. Knucklehead walks into a bank with a telephone! Not a pistol, not a shotgun, but a fucking phone. Cleans the place out, doesn't even lift a fucking finger. Did they hurt the little girl? I don't know, there probably never was a little girl in the first place. The point of the story isn't the little girl, the point of the story is, they robbed a bank with a telephone.",
	
	"Now boys, listen up. We're going to a place called Monster Joe's Truck and Tow. I'll drive the tainted car. Jules, you ride with me. Vincent, you follow in my Acura. We run across the path of any John Q. Laws, nobody does a fucking thing unless I do it first. What did I just say? Don't do shit unless. Unless what? Unless you do it first. Spoken like a true prodigy. How about you, Lash LaRue? You think you can keep your spurs from jinglin' and janglin'? Look, Mr. Wolf, my gun went off, I don't know why, and now you're helping us out of the situation. I'm cool with it, all right? Fair enough. Now I drive real fucking fast, so keep up. I get my car back any differently than when I gave it, Monster Joe's gonna be disposing of two bodies.",
	
	"Who's she? Look, go to the fridge and get the thing with the O.D. adrenalin shot. What's wrong with her? She's O.D.ing! Get her the hell outta her! GET THE SHOT! Fuck you! Fuck you, too! What a fuckin' bitch! You just keep talking to her, all right? She's getting the shot, I'm gonna get my little black medical book. What the fuck do you need a medical book for? I've never had to give an adrenalin shot. You never give an adrenalin shot? I've never had to, all right! I don't go joy-poppin' with bubble-gummers! My friends can handle their highs! GET THE SHOT!",
	
	"Remember, I just got back from Amsterdam. Am I a nigger? Are we in Inglewood? No... You're in my home. White people who know the difference between good shit and bad shit, this is the house they come to. Now, my shit, I'll take the Pepsi challenge with that Amsterdam shit, any day of the fuckin' week. That's a bold statement. This ain't Amsterdam, Vince. This is a sellers market. Coke is fucking dead as... dead. Heroin, it's coming back in a big fucking way.",
	
	"I'm the manager here! There's no problem, no problem at all...You're gonna give me a problem? Noooo sir, I'm not! I'm not gonna give you any problem! You're gonna give me a problem? YOU ARE JUST GONNA GIVE ME A FUCKING PROBLEM! YOU ARE GONNA GIVE ME A FUCKING PROBLEM! Get- I don't know Honey Bunny, he looks like the hero type to me! Well, just EXECUTE him! I am not a hero, I'm just a coffee shop-",
	
	"You must be Jules, which would make you Vincent. Let's get down to brass tacks, gentlemen. If I was informed correctly, the clock is ticking, is that right, Jimmie? Uh, one hundred percent. 30 in the AM, is that right? Uh-huh. I was led to believe that if she comes home and finds us here, she'd wouldn't appreciate it none too much? She wouldn't at that. That gives us exactly... forty minutes to get the fuck out of Dodge. Which, if you do what I say when I say it, should be plenty. Now, you've got a corpse in a car, minus a head, in a garage. Take me to it.",
	
	"Oh, fuck! I'm fucked. Oh, fuck! Oh, fuck! Is he a friend of yours? Hmm? Oh, Vincent, Marvin. Marvin, Vincent. Better tell him to shut the fuck up. He's gettin' on my nerves! Marvin? Marvin... MARVIN! I'd knock that shit off if I was you.",
	
	"Did you bring the watch? I believe so. You believe so? You 'believe' so? What the fuck does that mean? You either did, or you didn't! Then I did. Are you sure? No...Fuck! Motherfucking shit! Do you fucking know how fucking stupid you are? Shit! Fuck! It's not your fault."	
	];

//module.exports.largeParagraph = largeParagraph;